name: Build & Push HTMX Frontend Image

on:
  push:
    branches: [main]
    paths:
      - 'microservice_example/htmx_frontend/**'
  pull_request:
    branches: [main]
    paths:
      - 'microservice_example/htmx_frontend/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image tag
        id: vars
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/htmx_frontend:${{ env.SHORT_SHA }} microservice_example/htmx_frontend

      - name: Push Docker image (commit tag)
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/htmx_frontend:${{ env.SHORT_SHA }}

      - name: Make image public
        run: |
          curl -X PATCH \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/users/${{ github.repository_owner }}/packages/container/htmx_frontend/visibility \
            -d '{"visibility":"public"}'
